#!/usr/bin/env python3
"""
n8n Workflow Automation Bot
===========================
Converts plain-English workflow descriptions into live n8n workflows.

Modes:
  - Autonomous (GROQ_API_KEY set): generates JSON via Groq LLM automatically.
  - Claude Code mode (no key): paste the JSON generated by Claude in this chat.

Usage:
  python main.py
  python main.py --json path/to/workflow.json   # deploy a JSON file directly
"""
import json
import sys
import time
import argparse
from pydantic import ValidationError

from config import N8N_API_KEY, GROQ_API_KEY, MAX_RETRIES, N8N_BASE_URL
from n8n_client import N8nClient, N8nAPIError
from workflow_gen import generate_workflow, parse_and_validate, find_webhook_path
from models import N8nWorkflow

BANNER = """
╔══════════════════════════════════════════════════════╗
║         n8n Workflow Automation Bot                  ║
║  Describe a workflow → auto-deploy → auto-test       ║
╚══════════════════════════════════════════════════════╝
"""

MODE_NOTE_CLAUDE = """
[MODE] Claude Code — Paste workflow JSON below (no Groq key set).
       To enable autonomous mode, add GROQ_API_KEY to your .env file.
       Get a free key at https://console.groq.com
"""

MODE_NOTE_GROQ = f"""
[MODE] Autonomous (Groq) — just describe your workflow in plain English.
"""


def print_step(step: str, msg: str):
    icons = {"start": "▶", "ok": "✓", "err": "✗", "info": "ℹ", "poll": "⟳"}
    icon = icons.get(step, "•")
    print(f"  {icon} {msg}")


def read_multiline_input(prompt: str) -> str:
    """Read potentially multi-line input (JSON paste) until user types END on its own line."""
    print(prompt)
    lines = []
    while True:
        try:
            line = input()
        except EOFError:
            break
        if line.strip() == "END":
            break
        lines.append(line)
    return "\n".join(lines)


def deploy_and_test(client: N8nClient, workflow: N8nWorkflow) -> tuple[bool, str]:
    """
    Deploy, activate, and test a workflow.
    Returns (success: bool, error_message: str).
    """
    workflow_id = None
    try:
        # Step 1: Create
        print_step("start", f"Creating workflow '{workflow.name}'...")
        payload = workflow.to_api_dict()
        created = client.create_workflow(payload)
        workflow_id = created.get("id") or created.get("data", {}).get("id")
        if not workflow_id:
            return False, f"No workflow ID in response: {json.dumps(created)[:300]}"
        print_step("ok", f"Workflow created (id={workflow_id})")

        # Step 2: Activate
        print_step("start", "Activating workflow...")
        client.activate_workflow(workflow_id)
        print_step("ok", "Workflow activated")

        # Step 3: Trigger via webhook
        webhook_path = find_webhook_path(workflow)
        if not webhook_path:
            print_step("info", "No webhook trigger found — skipping test execution.")
            print_step("ok", f"Workflow live at: {N8N_BASE_URL}/workflow/{workflow_id}")
            return True, ""

        print_step("start", f"Triggering webhook: /webhook-test/{webhook_path}")
        trigger_start = time.time()
        trigger_result = client.trigger_webhook(webhook_path)
        print_step("ok", f"Webhook triggered. Response: {json.dumps(trigger_result)[:200]}")

        # Step 4: Poll for execution result
        print_step("poll", "Waiting for execution to complete...")
        execution = client.poll_for_execution(workflow_id, trigger_start)

        if execution is None:
            return False, "Execution did not complete within timeout"

        status = execution.get("status", "unknown")
        if status == "success":
            print_step("ok", f"Execution succeeded!")
            # Show last node output
            data = execution.get("data", {})
            result_data = data.get("resultData", {})
            last_node = result_data.get("lastNodeExecuted", "")
            run_data = result_data.get("runData", {})
            if last_node and last_node in run_data:
                last_output = run_data[last_node]
                print_step("info", f"Last node output ({last_node}):")
                print(f"     {json.dumps(last_output)[:500]}")
            print_step("ok", f"View workflow: {N8N_BASE_URL}/workflow/{workflow_id}")
            return True, ""
        else:
            error_msg = execution.get("data", {}).get("resultData", {}).get("error", {})
            if isinstance(error_msg, dict):
                error_msg = error_msg.get("message", str(error_msg))
            return False, f"Execution {status}: {error_msg}"

    except N8nAPIError as e:
        if workflow_id:
            print_step("info", f"Cleaning up failed workflow {workflow_id}...")
            client.delete_workflow(workflow_id)
        return False, f"n8n API error: {e}"
    except Exception as e:
        if workflow_id:
            client.delete_workflow(workflow_id)
        return False, f"Unexpected error: {e}"


def run_interactive(client: N8nClient, autonomous: bool):
    """Main interactive loop."""
    print(BANNER)
    print(f"  n8n instance: {N8N_BASE_URL}")
    print(MODE_NOTE_GROQ if autonomous else MODE_NOTE_CLAUDE)

    while True:
        print("\n" + "─" * 54)
        if autonomous:
            try:
                description = input("Describe your workflow (or 'quit'): ").strip()
            except (EOFError, KeyboardInterrupt):
                print("\nGoodbye!")
                break
            if description.lower() in ("quit", "exit", "q"):
                print("Goodbye!")
                break
            if not description:
                continue
        else:
            print("Paste your workflow JSON below.")
            print("(Type END on its own line when done, or 'quit' to exit)\n")
            raw = read_multiline_input("> ")
            if raw.strip().lower() in ("quit", "exit", "q", ""):
                if raw.strip().lower() in ("quit", "exit", "q"):
                    print("Goodbye!")
                    break
                continue
            description = raw

        prev_json = ""
        error = ""
        success = False

        for attempt in range(1, MAX_RETRIES + 1):
            if attempt > 1:
                print(f"\n  [Retry {attempt}/{MAX_RETRIES}] Regenerating workflow with error context...")

            # Generate / parse workflow
            try:
                if autonomous:
                    workflow = generate_workflow(description, prev_json=prev_json, error=error)
                else:
                    workflow = parse_and_validate(description if attempt == 1 else prev_json)
            except (json.JSONDecodeError, ValidationError, ValueError) as e:
                print_step("err", f"Workflow validation failed: {e}")
                if not autonomous:
                    print("  Please fix the JSON and try again.")
                    break
                error = str(e)
                prev_json = description
                continue

            print_step("info", f"Workflow '{workflow.name}' validated ({len(workflow.nodes)} nodes)")

            # Deploy and test
            success, error = deploy_and_test(client, workflow)
            if success:
                break

            print_step("err", f"Deployment/execution failed: {error}")
            prev_json = json.dumps(workflow.to_api_dict(), indent=2)

            if not autonomous:
                print("  Automatic retry requires Groq API key. Please fix and re-paste.")
                break

        if not success and attempt == MAX_RETRIES:
            print_step("err", f"Failed after {MAX_RETRIES} attempts. Last error: {error}")
            print("  Try rephrasing your workflow description.")


def run_from_file(client: N8nClient, json_path: str):
    """Deploy a workflow from a JSON file directly."""
    print(f"Loading workflow from {json_path}...")
    with open(json_path) as f:
        raw = f.read()

    workflow = parse_and_validate(raw)
    print_step("info", f"Workflow '{workflow.name}' validated ({len(workflow.nodes)} nodes)")
    success, error = deploy_and_test(client, workflow)
    if not success:
        print_step("err", f"Failed: {error}")
        sys.exit(1)


def main():
    parser = argparse.ArgumentParser(description="n8n Workflow Automation Bot")
    parser.add_argument("--json", metavar="FILE", help="Deploy a workflow from a JSON file")
    args = parser.parse_args()

    if not N8N_API_KEY:
        print("ERROR: N8N_API_KEY not set. Copy .env.example to .env and add your key.")
        sys.exit(1)

    client = N8nClient()
    autonomous = bool(GROQ_API_KEY)

    if args.json:
        run_from_file(client, args.json)
    else:
        run_interactive(client, autonomous)


if __name__ == "__main__":
    main()
