"""
Workflow generator: uses Groq (free LLM API) to generate n8n workflow JSON
from plain-English descriptions. Falls back to requesting manual JSON input
if no Groq API key is configured.

In "Claude Code mode" (no GROQ_API_KEY), the caller provides pre-generated JSON
(from Claude Code's direct output) and this module only validates it.
"""
import json
import uuid
from openai import OpenAI
from config import GROQ_API_KEY, GROQ_MODEL
from models import N8nWorkflow, N8nNode

SYSTEM_PROMPT = """You are an n8n workflow architect. Generate valid n8n workflow JSON from user descriptions.

CRITICAL RULES:
1. Every workflow MUST start with a Webhook trigger node for testability.
   Use type: "n8n-nodes-base.webhook", typeVersion: 2
   Set parameters: {"httpMethod": "POST", "path": "<unique-slug>", "responseMode": "responseNode"}

2. Node IDs must be unique UUIDs (e.g. "a1b2c3d4-e5f6-7890-abcd-ef1234567890")

3. Connections format:
   {
     "SourceNodeName": {
       "main": [[{"node": "TargetNodeName", "type": "main", "index": 0}]]
     }
   }

4. Position nodes left-to-right with 200px spacing starting at [250, 300]

5. For HTTP requests use: "n8n-nodes-base.httpRequest" typeVersion: 4.2
   parameters: {"method": "GET", "url": "...", "options": {}}

6. For Set/transform data: "n8n-nodes-base.set" typeVersion: 3.4
   parameters: {"mode": "manual", "assignments": {"assignments": [{"id": "1", "name": "field", "value": "={{$json.field}}", "type": "string"}]}}

7. Return ONLY raw JSON — no markdown, no explanation, no code fences.

8. Always end with a "Respond to Webhook" node:
   type: "n8n-nodes-base.respondToWebhook" typeVersion: 1
   parameters: {"respondWith": "json", "responseBody": "={{JSON.stringify($json)}}"}

JSON structure:
{
  "name": "Workflow Name",
  "nodes": [...],
  "connections": {...},
  "settings": {"executionOrder": "v1"}
}"""

DEBUG_SUFFIX = """
The previous workflow had this error: {error}

The previous workflow JSON was:
{prev_json}

Fix all issues and return corrected workflow JSON only."""


def _generate_via_groq(description: str, prev_json: str = "", error: str = "") -> str:
    """Call Groq API to generate workflow JSON."""
    client = OpenAI(
        api_key=GROQ_API_KEY,
        base_url="https://api.groq.com/openai/v1",
    )

    user_message = description
    if prev_json and error:
        user_message += DEBUG_SUFFIX.format(error=error, prev_json=prev_json)

    response = client.chat.completions.create(
        model=GROQ_MODEL,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_message},
        ],
        temperature=0.2,
        max_tokens=4096,
    )
    return response.choices[0].message.content.strip()


def generate_workflow(description: str, prev_json: str = "", error: str = "") -> N8nWorkflow:
    """
    Generate and validate an N8nWorkflow from a plain-English description.

    In autonomous mode (GROQ_API_KEY set): calls Groq to generate JSON.
    In Claude Code mode: expects description to be pre-generated JSON (paste mode).
    """
    if GROQ_API_KEY:
        raw = _generate_via_groq(description, prev_json, error)
    else:
        # Claude Code mode: the description IS the JSON (generated by Claude in-chat)
        raw = description

    return parse_and_validate(raw)


def parse_and_validate(raw_json: str) -> N8nWorkflow:
    """Parse raw JSON string into a validated N8nWorkflow."""
    # Strip markdown code fences if present
    raw = raw_json.strip()
    if raw.startswith("```"):
        lines = raw.split("\n")
        raw = "\n".join(lines[1:-1] if lines[-1] == "```" else lines[1:])

    data = json.loads(raw)

    # Ensure all nodes have UUIDs
    for node in data.get("nodes", []):
        if not node.get("id"):
            node["id"] = str(uuid.uuid4())

    workflow = N8nWorkflow(**data)

    connection_errors = workflow.validate_connections()
    if connection_errors:
        raise ValueError("Connection validation errors:\n" + "\n".join(connection_errors))

    return workflow


def find_webhook_path(workflow: N8nWorkflow) -> str | None:
    """Extract the webhook path from a workflow's webhook trigger node."""
    for node in workflow.nodes:
        if "webhook" in node.type.lower() and node.type != "n8n-nodes-base.respondToWebhook":
            path = node.parameters.get("path")
            if path:
                return str(path)
    return None
