"""Shared test fixtures."""
import pytest


@pytest.fixture
def sample_apd_text():
    return (
        "APD,ITEM NAME:HOLDBACK;DRAWING NUMBER:4802-1594;POSITION OR ITEM NUMBER:P3;REVISION:0\n"
        "APD,ITEM NAME:FLANGE;DRAWING NUMBER:4802-1595;POSITION OR ITEM NUMBER:P1;REVISION:1;MATERIAL:42CRMO4V\n"
        "APD,ITEM NAME:BOLT;DRAWING NUMBER:4802-1594;POSITION OR ITEM NUMBER:P4;REVISION:0\n"
    )
